<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>program_ns</RootNamespace>
    <Platforms>x86;AnyCPU</Platforms>
    <AssemblyName>can-connector</AssemblyName>
    <ApplicationIcon>custom-power.ico</ApplicationIcon>
    <Nullable>enable</Nullable>
    <StartupObject>program_ns.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="custom-power.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Collections.Immutable" Version="8.0.0" />
    <PackageReference Include="Tomlyn" Version="0.17.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\lib\lib-komodo-can\lib-komodo-can\lib-komodo-can.csproj" />
    <ProjectReference Include="..\..\lib\lib-serial\lib-serial\lib-serial.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="gui\config-resolve.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="config-GE-Healthcare.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-three-customer.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-avd-one-programmer.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-avd-one-customer.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-ga-lifepo-next.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-ga-lifepo-next-bootloader.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-sikorsky-one-bootloader.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-sikorsky-one.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-avd-one.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-universal-tester.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-three-charger.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-two-afe-customer.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-two-afe.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-three.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-ga-lifepo.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-egalet.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-two-lite-customer.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-two-lite.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-one-customer.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="config-aerosonde-one.toml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Dust_2ndSector_06072021.hex">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>