[general]
title = "General Atomics P3E (STM32L431) Pack Bootloader GUI"
device = "GA_LiFePO4_Next"

[serial]
channel = 0
default-baud-rate = 115_200
data-bits = 8
parity = "none"
stop-bits = "one"
handshake = "none"

[bootloader]
hex-file-content = [ { max-size = 212_992, signature = "custom-power-general-atomics-LiFePO4-8S9P" } ]
upgrade-tasks = [ { firmware-index = 0, id-prefix = 0x1CAB0000 } ]
reboot-time = 1_000
normal-timeout = 30_000
verify-timeout = 45_000
auto-exit = true
