[general]
title = "General Atomics P3E (STM32L431) Pack GUI"
device = "GA_LiFePO4_Next"

[modbus]
translator = "GA_LiFePO4_Next_Modbus"
default-baud-rate = 9_600
data-bits = 8
parity = "even"
stop-bits = "one"
handshake = "none"
