[general]
title = "Avery Dennison 2S"
device = "Avd_One"

[serial]
channel = 0
default-baud-rate = 9_600
data-bits = 8
parity = "none"
stop-bits = "one"
handshake = "none"

[avd]
commands-password = "poweroverwhelming"
programmer = false
