<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <RootNamespace>GEHC_Forms_GUI</RootNamespace>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="System.IO.Ports" Version="8.0.0" />
      <PackageReference Include="Tomlyn" Version="0.19.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="images\" />
    </ItemGroup>

    <ItemGroup>
      <None Include="Battery_Info.csv">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
      <None Include="config.toml">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>